docsファイル修正
bs-htanaka/training-app pull request #1
Opened 2020-03-03 09:21 UTC by bs-htanaka

マークダウン形式採用
初めてのプルリク

2020-03-03 09:46 UTC, kiarina requested changes
- Pull Request のコメントは Markdown 記法が使えます
- この Pull Request が何のための Pull Request なのか書きましょう
- おそらく、これは課題の Step3 だと思いますが、docs はディレクトリという指示ではなかったでしょうか？

以上、確認お願いします。

2020-03-04 01:53 UTC, bs-htanaka commented
#### 課題ステップ3のdocsディレクトリ追加

- docsファイルを削除して新たにdocsディレクトリを作成しました。

確認お願いします

2020-03-04 02:22 UTC, kiarina requested changes
@bs-htanaka 
docs ディレクトリ以下にファイルが格納されたのを確認しました。
ありがとう！

次ですが、`.DS_Store` がコミットに含まれてしまっています。
このファイルは不要なので .gitignore ファイルで除外してください。

2020-03-04 02:52 UTC, bs-htanaka commented
#### .DS_Storeのコミット除外
- .gitignoreファイルに.DS_Storeを追記して除外できました。

確認お願いします。

2020-03-04 02:55 UTC, kiarina approved these changes
LGTM

2020-03-04 03:28 UTC, merged